title: TRFRM-AZ
description: Plataforma de Laboratorios · Terraform en Azure Essentials
# Para project site:
url: "https://jorgepas12.github.io"
baseurl: "/webpagesrepo"

logo: /assets/img/netec-logo.png