# .github/workflows/build.yml
name: Build Jekyll

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'   # o la que uses
          bundler-cache: true

      - name: Install gems
        run: bundle install --path vendor/bundle

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace
